config/routes.rb
SampleApp::Application.routes.draw do
  get "reviews/create"

  get "reviews/destroy"

  match "/ingredient_recipes/:id", to: 'ingredient_recipes#destroy'
  match "/ingredient_shopping_lists/:id", to: 'ingredient_shopping_lists#destroy'

  get "ingredient_shopping_lists/destroy"

  get "ingredient_users/destroy"

  get "ingredients/index"

  get "ingredients/show"

  get "ingredients/create"

  get "ingredients/destroy"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:create, :destroy, :show, :index]
  resources :shopping_lists, only: [:create, :destroy, :show]
  resources :ingredients, only: [:create, :destroy, :show]
  resources :ingredient_users, only: [:destroy]
  resources :ingredient_recipes, only: [:destroy]
  resources :ingredient_shopping_lists, only: [:destroy]
  resources :reviews, only: [:create]
  
  root to: 'static_pages#home'
  
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/trololo', to: 'static_pages#trololo'
  match '/report', to: 'static_pages#report'
  match '/add_ingredient', to: 'ingredients#new_ingredient_user'
  match '/users/create_ingredient_user', to: 'ingredients#create_ingredient_user'
  match '/ingredients/create_ingredient_recipe', to: 'ingredients#create_ingredient_recipe'
  match '/ingredients/create_ingredient_shopping_list', to: 'ingredients#create_ingredient_shopping_list'
  match '/recipes_possible', to: 'users#recipes_possible'
  match '/recipes_expiring', to: 'users#recipes_exp'
  match '/ingredients_expiring', to: 'users#ingredients_exp'
  match '/create_review', to: 'reviews#create'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, :name, :prep_time

  belongs_to :user
  validates :user_id, presence: true


  has_many :ingredients, :through => :ingredient_recipes
  has_many :ingredient_recipes, dependent:  :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :signed_in_user, only: [ :create, :destroy ]
  before_filter :correct_user, only: :destroy


  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
    @ingredients = @recipe.ingredients
    @reviews = @recipe.reviews
    sum = 0
    for r in @reviews
      sum += r.rating
    end
    if (@reviews.length == 0)
    @mean = 0
    else
    @mean = sum / (@reviews.length)
    end
  end

  def create
    @recipe = current_user.recipes.build(params[:recipe])
    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_url

  end

  private

  def correct_user
    @recipe = current_user.recipes.find_by_id(params[:id])
    redirect_to root_url if @recipe.nil?
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<li>
  <span class="content"><%= recipe.name %></span>
  <span class="content"><%= recipe.prep_time %></span>
  <span class="content"><%= recipe.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(recipe.created_at) %> ago.
  </span>
  <% if current_user?(recipe.user) %>
      <%= link_to "delete", recipe, method: :delete,
                  data: { confirm: "You sure?" },
                  title: recipe.name %>
  <% end %>
</li>

app/views/recipes/index.html.erb
  <% for recipe in @recipes %>

        <span class="content"><%= link_to recipe.name,recipe, :class => 'btn' %>

        <% if current_user?(recipe.user) %>
            <%= link_to "delete", recipe, method: :delete,
                        data: {confirm: "You sure?"},
                        title: recipe.name,
                        :class => 'btn btn-danger'%>
        <% end %>
          </span>
      <br>

  <% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<div class="span12">
  <h3>Prep Time: </h3>

  <p><%= @recipe.prep_time %></p>

  <h3> Directions: </h3>

  <p><%= @recipe.description %></p>
          <br>
  <h3>Average Rating: <%= @mean %></h3>
       <br>


  <% if @ingredients %>
      <h3>Ingredients (<%= @recipe.ingredients.count %>)</h3>
      <ol>

        <% for ingredient in @ingredients %>
            <li>

              <p><%= image_tag(ingredient.picture, :size => "50x50") %></p>

              <p><%= ingredient.name %>,
                Amount: <%= @recipe.ingredient_recipes.find_by_ingredient_id(ingredient.id).amount %>
                <% if current_user?(@recipe.user) %>
                    <%= link_to 'Delete', ingredient_recipe_path(@recipe, :ingredient_id => ingredient.id), :method => :post, :class => 'btn btn-danger', :confirm => "Are you sure?" %> </p>
                <% end %>
                </li>


        <% end %>

      </ol>
  <% end %>

  <br><br>


  <% if @reviews %>
      <% x =0 %>
      <div class="pull-right span12">
     <h3>Reviews</h3>
      <% for review in @reviews %>

             <h4> <%= x = x+1 %> . </h4> <p>Rating: <%= review.rating %></p>

             <p>Description: </p>
             <p><%= review.description %></p>
      <% end %>

      </div>
  <% end %>


  <% if current_user?(@recipe.user) %>
      <h1>Add Ingredient</h1>
      <%= form_tag("/ingredients/create_ingredient_recipe", :method => "post") do %>


          <p>
            Name:
            <%= text_field_tag :name %>
          </p>

          <p>
            Amount
            <%= text_field_tag :amount %>
          </p>
          <%= hidden_field_tag 'id', params[:id] %>
          <p>
            <%= submit_tag 'Create' %>
          </p>

          <% end %>
      <% end %>

  <h1>Add Review</h1>

  <%= form_tag("/create_review", :method => "post") do %>
      <p>Rating: Enter a value between 1 and 5</p>
      <%= text_field_tag :rating%>
      <p>Description</p>
      <%= text_area_tag :description %>
      <%= hidden_field_tag 'id', params[:id] %>
      <%= submit_tag 'Create' %>


  <% end %>


  </div>