config/routes.rb
SampleApp::Application.routes.draw do
  get "reviews/create"

  get "reviews/destroy"

  match "/ingredient_recipes/:id", to: 'ingredient_recipes#destroy'
  match "/ingredient_shopping_lists/:id", to: 'ingredient_shopping_lists#destroy'

  get "ingredient_shopping_lists/destroy"

  get "ingredient_users/destroy"

  get "ingredients/index"

  get "ingredients/show"

  get "ingredients/create"

  get "ingredients/destroy"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:create, :destroy, :show, :index]
  resources :shopping_lists, only: [:create, :destroy, :show]
  resources :ingredients, only: [:create, :destroy, :show]
  resources :ingredient_users, only: [:destroy]
  resources :ingredient_recipes, only: [:destroy]
  resources :ingredient_shopping_lists, only: [:destroy]
  resources :reviews, only: [:create]
  
  root to: 'static_pages#home'
  
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/trololo', to: 'static_pages#trololo'
  match '/report', to: 'static_pages#report'
  match '/add_ingredient', to: 'ingredients#new_ingredient_user'
  match '/users/create_ingredient_user', to: 'ingredients#create_ingredient_user'
  match '/ingredients/create_ingredient_recipe', to: 'ingredients#create_ingredient_recipe'
  match '/ingredients/create_ingredient_shopping_list', to: 'ingredients#create_ingredient_shopping_list'
  match '/recipes_possible', to: 'users#recipes_possible'
  match '/recipes_expiring', to: 'users#recipes_exp'
  match '/ingredients_expiring', to: 'users#ingredients_exp'
  match '/create_review', to: 'reviews#create'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ReciMe by Sean Freiburg, Brian Hauger, Cesar "Vinny" Martinez, and Kenny Nsofor
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to 'Report', '/report' %></li>
      <li><%= link_to "Trololo", '/trololo' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ReciMe", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
              <li> <%= link_to "Recipes", recipes_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
            <%=  %>
		</div>
	</body>
</html>